name: CI-Client

on:
  push:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build -t leaguelugas/store-7-client .
        working-directory: ./client

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: leaguelugas/store-7-client
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: client
